services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "9080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M

  config-server:
    build: ./config-server # Path to Dockerfile context
    ports:
      - "8888:8888"
    volumes:
      - ./config-server/config-repo:/etc/config-repo # Mount your local config-repo
      # Ensure Config Server's search-locations points to /etc/config-repo
    environment:
      # If config server's search-locations is parameterized or needs env var
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:///etc/config-repo
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8888/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M

  eureka-client:
     build: ./eureka-client
     depends_on:
       eureka-server:
        condition: service_healthy
     deploy:
       resources:
         limits:
           memory: 256M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  zipkin-server:
    image: openzipkin/zipkin:3.4
    ports:
      - "9411:9411"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:9411/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1 # Güncel stabil bir sürüm kullanılıyor
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    depends_on:
      #      - elasticsearch
      mysql-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M

  kafka:
    image: confluentinc/cp-kafka:7.9.1 # Güncel stabil bir sürüm kullanılıyor
    container_name: kafka
    ports:
      - "9092:9092" # Docker ağı dışındaki istemciler için
      - "29092:29092" # Docker ağı içindeki istemciler için (örn. diğer konteynerler)
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1 # Confluent'e özgü
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1 # Confluent'e özgü
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1             # Confluent'e özgü
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  # Confluent'e özgü
    deploy:
      resources:
        limits:
          memory: 1024M

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    ports:
      - "8988:8080" # AKHQ UI, ana makine portu 8088'de erişilebilir olacak
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-cluster:
              properties:
                bootstrap.servers: "kafka:29092" # AKHQ için Kafka dahili Docker ağ adresi
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 256M

  product-service:
    build: ./product-service
#    ports:
#      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M

  order-service:
    build: ./order-service
 #   environment:
 #     - LOGSTASH_HOST=logstash
 #     - LOGSTASH_PORT=5000
    ports:
      - "8090:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      #      logstash:
      #        condition: service_healthy
  #    zipkin-server:
  #      condition: service_healthy
    #      keycloak:
    #        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M

  inventory-service:
    build: ./inventory-service
    ports:
      - "8100:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M

  payment-service:
    build: ./payment-service
    ports:
      - "8110:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M

  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cokgizlisifre
      - MYSQL_DATABASE=default_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pcokgizlisifre" ]
      timeout: 20s
      retries: 10


volumes:
  mysql_data:
  prometheus_data:
  grafana_data:

